# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# scan with Anchore's Syft tool, and uploads the results to the GitHub Dependency
# submission API.

# For more information on the Anchore sbom-action usage
# and parameters, see https://github.com/anchore/sbom-action. For more
# information about the Anchore SBOM tool, Syft, see
# https://github.com/anchore/syft
name: Bogazici-DevSecOps-Pipeline

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
 build-and-syft:
  name: Build & SBOM
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t juice-shop:${{ github.sha }} .

    - name: Syft SBOM Scan
      uses: anchore/sbom-action@v0
      with:
        image: "juice-shop:${{ github.sha }}"
        output-file: "sbom.spdx.json"
        format: "spdx-json"

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v2
        with:
          config: "p/ci"        # veya kendi kuralların: ./semgrep-rules
          output: semgrep-results.json
          json: true

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json

